---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    checks:
      no-unused-expressions:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths:
- dist/
- node_modules/
- webpack.config.js
